name = "gt_ai_gateway_test"
main = "src/index.ts"
compatibility_date = "2025-01-19"

compatibility_flags = [ "nodejs_compat", "no_handle_cross_request_promise_resolution" ]

[vars]
ROOT_TOKEN = "root-token-123"
TEST_MODE = "worker"

[[d1_databases]]
binding = "DB"
database_name = "gt_ai_gateway_test"
database_id = "test-database-id"

[observability]
enabled = true
head_sampling_rate = 1

[assets]
directory = "frontend/dist"
binding = "ASSETS"