name = "gt-ai-gateway"
main = "src/index.ts"
compatibility_date = "2025-01-19"

compatibility_flags = [ "nodejs_compat", "no_handle_cross_request_promise_resolution" ]


[vars]
# ROOT_TOKEN = "your-root-token-here"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "gt_ai_gateway"
database_id = "def7d6fc-a072-4feb-bda0-d6860fab106e"

# [ai]
# binding = "AI"

[observability]
enabled = true
head_sampling_rate = 1

[assets]
directory = "frontend/dist"
binding = "ASSETS"
